### ISSUE TITLE
Change configuration of mongo provider

### ISSUE THREAD

**Issue by KamilWojciech** [Schibsted-Tech-Polska/stp.svd-scheduler-bundle#16]
We should allow user to set his own configuration like: 
```yml
svd_scheduler:
    job_provider:
        provider: svd_scheduler.job_provider.odm
        config: 
            db: ...
            password: ...
            username: ...
            collection: ...
            ...
    processes_limit:                    4
```
